Relate user models
oursky/django-material-demo pull request #38
Opened 2022-09-05 03:19 UTC by Rubikium

connect oursky#24

2022-09-05 14:03 UTC, Steven-Chan requested changes
I run into the following error when running migration.

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/12228201/188464467-91fdc2e5-e546-4ee6-bacc-de5a874f2c2a.png">

`0011_remove_user_id_alter_user_account` is not a complete migration. In the previous migration, the column `polls_user.account_id` is nullable. But the next migration it becomes a one to one field, which is not nullable. That means there is missing data you need to include in this migration before altering the column to non-nullable.

You may need to run raw SQL in the migration, pls take a look at https://docs.djangoproject.com/en/4.1/ref/migration-operations/#runsql. Remember that the migration needs to be reversible.

2022-09-05 14:14 UTC, Steven-Chan commented
And sadly when I try the revert `0010_remove_user_email_remove_user_name_user_account`, I run into another error.

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/12228201/188467709-bb7bb249-e147-47f2-9fea-79f960850d92.png">

`polls_user.name` was not nullable. If you simply remove the column but do not provide a reversible version, it will fail because the default value is null.

Please fix these two migrations.

2022-09-06 09:22 UTC, Rubikium commented
Migration `0010` should now be fixed, but I deleted migration `0011` for now since I haven't found a way to make changing `pk` fields reversible. This currently only affects the urls for user view/edit/delete pages since the urls correspond to the `pk` and not the `account_id` of the user object

2022-09-06 10:17 UTC, Steven-Chan approved these changes

2022-09-06 10:17 UTC, merged